wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    code_path: code/src/train.py
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1671467445.475593
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.10.6
      5: 0.13.6
      6: 4.25.1
      8:
      - 5
