wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.6
    start_time: 1671468762.703258
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.6
      5: 0.13.6
      6: 4.25.1
      8:
      - 5
adamw_config/lr:
  desc: null
  value: 0.001
adamw_config/weight_decay:
  desc: null
  value: 0.0001
d_model:
  desc: null
  value: 768
decoder_config/layer_config/attention_config/d_model:
  desc: null
  value: 768
decoder_config/layer_config/attention_config/dropout:
  desc: null
  value: 0.1
decoder_config/layer_config/attention_config/num_heads:
  desc: null
  value: 8
decoder_config/layer_config/intermediate_config/d_intermediate:
  desc: null
  value: 3072
decoder_config/layer_config/intermediate_config/d_model:
  desc: null
  value: 768
decoder_config/layer_config/intermediate_config/dropout:
  desc: null
  value: 0.1
decoder_config/num_layers:
  desc: null
  value: 6
decoder_config/pos_encoding_config/dropout:
  desc: null
  value: 0.1
decoder_config/pos_encoding_config/max_seq_len:
  desc: null
  value: 512
encoder_config/layer_config/attention_config/d_model:
  desc: null
  value: 768
encoder_config/layer_config/attention_config/dropout:
  desc: null
  value: 0.1
encoder_config/layer_config/attention_config/num_heads:
  desc: null
  value: 8
encoder_config/layer_config/intermediate_config/d_intermediate:
  desc: null
  value: 3072
encoder_config/layer_config/intermediate_config/d_model:
  desc: null
  value: 768
encoder_config/layer_config/intermediate_config/dropout:
  desc: null
  value: 0.1
encoder_config/num_layers:
  desc: null
  value: 6
encoder_config/pos_encoding_config/dropout:
  desc: null
  value: 0.1
encoder_config/pos_encoding_config/max_seq_len:
  desc: null
  value: 512
warmup_scheduler_config/warmup_steps:
  desc: null
  value: 4000
